# Generated by Django 6.0.5 on 2026-05-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('user_id', models.IntegerField()),
                ('merchant_id', models.IntegerField()),
                ('amount', models.FloatField()),
                ('category', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=2)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'timestamp'], name='idx_user_timestamp'), models.Index(fields=['country_code', 'user_id'], name='idx_country_user')],
            },
        ),
    ]
